language: node_js
node_js:
  - "node"
  - 4
  - 6
cache:
  directories:
    - node_modules
    - client/node_modules
sudo: required
install:
  - npm install
  - cd client && npm install
env:
  - NODE_ENV=CI
script:
  - cd .. && npm test
  - cd client && npm test
  - npm run build