// CMS
// Router actions
export const NAVIGATE = 'NAVIGATE'

// Flavours actions
export const ADD_FLAVOUR = 'ADD_FLAVOUR'
export const ADD_FLAVOUR_REQUEST = 'ADD_FLAVOUR_REQUEST'
export const GET_FLAVOURS_REQUEST = 'GET_FLAVOURS_REQUEST'
export const SET_FLAVOURS = 'SET_FLAVOURS'
export const TOGGLE_FLAVOUR_FORM = 'TOGGLE_FLAVOUR_FORM'

// Juices actions
export const ADD_JUICE = 'ADD_JUICE'
export const ADD_JUICE_REQUEST = 'ADD_JUICE_REQUEST'
export const GET_JUICES_REQUEST = 'GET_JUICES_REQUEST'
export const SET_JUICES = 'SET_JUICES'
export const TOGGLE_JUICE_FORM = 'TOGGLE_JUICE_FORM'

// TABLET
//Search actions
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SET_RESULTS = 'SET_RESULTS'
export const TOGGLE_FLAVOUR = 'TOGGLE_FLAVOUR'
export const TOGGLE_RESULTS = 'TOGGLE_RESULTS'
export const TOGGLE_SEARCH_FLAVOUR = 'TOGGLE_SEARCH_FLAVOUR'
export const TOGGLE_SEARCH_FLAVOUR_REQUEST = 'TOGGLE_SEARCH_FLAVOUR_REQUEST'
